#!/bin/bash

set -e

cd commits
./gradlew fatJar

export REPO_EXCLUDE=single-json-header,rust-lib-doc,store,scala-book,rime-wubi86-jidian,glm-headers,test,stb-image-single-header,sqlite3-lib,ndk-libmagic,zhc-C99,mathematica,store,bczhc,bczhc.github.io,world

java -jar build/libs/commits-all.jar

cd ..
mv commits/atimes .
