#!/bin/bash

set -e

cd github-api
./gradlew fatJar

export REPO_EXCLUDE=single-json-header,rust-lib-doc,store,scala-book,glm-headers,test,stb-image-single-header,sqlite3-lib,ndk-libmagic,store,bczhc,bczhc.github.io,world

java -jar build/libs/github-api-all.jar

cd ..
mv github-api/repos .

rm -rf cloned || true
mkdir cloned

while IFS= read -r repo; do
  git clone git@github.com:bczhc/"$repo" ./cloned/"$repo"
  git -C ./cloned/"$repo" log --format='%ai' --author='bczhc0@126.com' >> atimes
done < repos

rm -rf cloned
